package com.buildingblocks.movementsandtactics.domain.movements.events;

public enum EventsEnum {
  ADVANCED_BOX,
  VALIDATED_PIECE_COLOR,
  CURRENT_SHIFT_CHECKED,
  EXECUTED_MOVEMENT,
  INVALID_MOVEMENT,
  VALIDATED_PIECE_TYPE,
  MOVED_PIECE,
  RECORDED_MOVEMENT,
  ASSIGNED_SHIFT,
  CHANGED_SHIFT,
  REGISTERED_SHIFT,
  UPDATED_BOX,
  UPDATED_MOVEMENT,
  VALIDATED_MOVEMENT,
  OCCUPIED_BOX,
  UNOCCUPIED_BOX
}
