package com.buildingblocks.movementsandtactics.domain.movements.events;

public enum EventsEnum {
  ADVANCED_BOX,
  COLOR_OF_VALIDATED_PART,
  CURRENT_SHIFT_CHECKED,
  EXECUTED_MOVEMENT,
  INVALID_MOVEMENT,
  PART_TYPE_VALIDATED,
  PIECE_MOVED,
  RECORDED_MOVEMENT,
  SHIFT_ASSIGNED,
  SHIFT_CHANGED,
  SHIFT_REGISTERED,
  UPDATED_BOX,
  UPDATED_MOVEMENT,
  VALIDATED_MOVEMENT,

}
